name: Build image

on:
  push:
    branches: [ master ]

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t "ghcr.io/stck/phantomjs-arm:latest" -f ./Dockerfile .
